### ISSUE TITLE
Link to source code on home page

### ISSUE THREAD

**Issue by Julian-O** [cgsecurity/testdisk_documentation#2]
The [Home Page for TestDisk](https://www.cgsecurity.org/wiki/TestDisk) says:

> TestDisk is OpenSource software [...]

But what it doesn't seem to say anywhere on the page is where the source is. This was a red flag - I was worried it might be malware given I couldn't initially work out how to inspect the code if I wanted to.

I suggest you include a link to the source, which I eventually found at https://github.com/cgsecurity/testdisk (and also to this documentation repository) to make sure people know where to find it.

**Comment by cgsecurity** [comment]
On the Home Page for TestDisk, there is a link "Download binary executables and source files for DOS, Win32, MacOSX and Linux.". On the download page, there are links to the git repository and source code archives.
I have added a link from "OpenSource software" to the git repository.
